version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_install:
      - "pip install pixi==0.48.1"
    post_install:
      - "pixi install --environment default"
    post_build:
      - "pixi run -e default sphinx-build -b html docs $READTHEDOCS_OUTPUT/html"
